### ISSUE TITLE
MineMenu keybindings cleared on restart

### ISSUE THREAD

**Issue by Foozey** [GirafiStudios/MineMenu#104]
Certain keybindings disappear after each restart (refreshing textures doesn't fix).

So far I've noticed this happening with any keybinds associated with Xaero's mods, and also any keybindings added by Personality from Team Abnormals.

**Comment by Foozey** [comment]
Something else I noticed with this is that Xaero's keybinds still stay in the `menu.json` file despite disappearing in-game. However, the keybindings from Personality get cleared completely from the `menu.json` file and don't come back.

**Comment by replicaJunction** [comment]
I've also run into this issue. I added the mod to MCEternal 1.4.3.1, which runs on Minecraft 1.12.2.

The mod version I'm using is `MineMenu-1.12.2-1.6.11-universal.jar`.

Any time I try to set up a keybinding for EnderIO's Dark Steel Armor, the binding works fine for that session, but the next time I start Minecraft fresh, the binding is gone (reset to empty and the default stone texture).

**Comment by Speecker** [comment]
Experiencing the same issue (1.6.11 as well).

**Comment by AndreySlower** [comment]
same

**Comment by DoomRater** [comment]
All of my Ender IO bindings disappear in a 1.12.2 instance.  They were being kept inside of a menu.  But other keybinds inside of menus are not disappearing...
