### ISSUE TITLE
Not an real issue but an idea!

### ISSUE THREAD

**Issue by Lukefreedner** [GirafiStudios/MineMenu#106]
Could you maybe add the option to have multiple radial menus?
I changing my commands very often when I'm working on different things and I thought, how cool would it be if I could press the menu button and then scroll through different menus. Just like the emote menu from Fortnite or pinging menus in games like Apex  Legends or Valorant. I think that that would be great because it would make using programs like Worldedit and other plugins so much more enjoyable. I don't know much about modding but I think that wouldn't even be that complicated to add.

Would love to see this feature coming to minemenu!

**Comment by GirafiStudios** [comment]
Thank you for the suggestion!
You can add sub-radial menus, within the radial menu already, to allow for something like this.
Anything further than that, is not going to happen.

**Comment by Lukefreedner** [comment]
how

**Comment by Lukefreedner** [comment]
oh i found it thanks
