### ISSUE TITLE
Searching for icons is very slow

### ISSUE THREAD

**Issue by replicaJunction** [GirafiStudios/MineMenu#107]
When setting an icon for a menu entry, searching for an icon is very slow. Each time I press a letter, there's a long pause before the list is filtered down.

That part I can understand - I'm playing in a large modpack with a lot of images - but the issue is that if I already know what I want, I'll start typing a word and the GUI will pause like this after each character, long after I've pressed it. My guess is that each time a character is typed, the screen filters down the item list all over again based on the current text in the box.

My suggestion would be to delay the behavior of filtering down the list of item images until the user hasn't typed any characters for some amount of time. Maybe 500ms or so. Too high and the screen would feel laggy for a different reason, but too low and it doesn't address this issue.

On a side note, I'd like to say a large thank you for this mod. I deal with some wrist issues that make it tough for me to use a traditional keyboard, and this mod helps keep me from constantly rebinding keys back and forth. I very much appreciate your work on this!

**Comment by GirafiStudios** [comment]
According to your message on the other issue, you're playing on 1.12.2, which have not been supported for years.

**Comment by replicaJunction** [comment]
That's fair, but the behavior I described still seems to be present in the master branch.

[1.12.2](https://github.com/GirafiStudios/MineMenu/blob/2b19fac77eeada86a51900566e16ff309402d0a1/src/main/java/dmillerw/menu/gui/menu/GuiPickIcon.java#L93-L103)

[master](https://github.com/GirafiStudios/MineMenu/blob/b884e4f1356d8a6c7dc02840fe4f7869c932c2dd/src/main/java/dmillerw/menu/gui/menu/PickIconScreen.java#L109-L114)

Even if you won't backport a fix to a 1.12 version, maybe you'd consider fixing the issue for the latest version of the mod?
