### ISSUE TITLE
Client Side Commands

### ISSUE THREAD

**Issue by sharkside85** [GirafiStudios/MineMenu#111]
Does MineMenu work with client-side mod commands? For instance, the keystrokes mod config is opened with running /keystrokes. However, when used in minemenu, it appears as an "unknown command" in chat, but when run in regular chat, it works. Is there a fix to this?  I am using the 1.8.9 version of minemenu.

**Comment by GirafiStudios** [comment]
They´re registering their command poorly.
Also 1.8.9 is not supported anymore (Wasn´t at the time of creating the issue either)
