### ISSUE TITLE
Forge/fabric?

### ISSUE THREAD

**Issue by SylisMC** [GirafiStudios/MineMenu#117]
Hey, couldn't remember if this was for forge or fabric. but curse forge decided to do a stupid thing again... they have removed the fabric tag, so now its unclear if something is for forge or fabric unless it specifically says so on the disruption page, had to find out from trying it. 
~Thanks

**Comment by GirafiStudios** [comment]
It´s only for Forge. Seems I forgot to set the "Forge"-tag on CurseForge for the latest 1.17.1 release.
There is an unofficial Fabric version by UltraBlack_ though (Gave him permission to do the port): https://www.curseforge.com/minecraft/mc-mods/minemenufabric
