### ISSUE TITLE
Using the configuration system in-game seems to be placing new categories at top of the file rather than at bottom as would be expected.

### ISSUE THREAD

**Issue by Kaleidio** [GirafiStudios/MineMenu#123]
might be enhancement only, but I'm still testing; it might actually be breaking the config loading which causes the binding issues that cause graphical corruption issues in #120 #121 #122

**Comment by GirafiStudios** [comment]
Mine Menu does not have an in-game config in 1.16.5, so not sure what you´re talking about here :)

**Comment by Kaleidio** [comment]
I'm talking about when you set a custom keybind using Shift + Click on the slot you wanna fill..  that's a "config" to me.  please reopen this issue.
