### ISSUE TITLE
[1.16.5] When a menu is bound to a quark mod key, the corresponding button fails

### ISSUE THREAD

**Issue by luoxiawuchen** [GirafiStudios/MineMenu#126]
Probably because the keys of the quark mod are different from other mods, when the menu binds the key bit of the quark, the game is reopened, and the bound menu is restored to a blank initial menu (even if the data in the json file still exists)

    "2": {
      "title": "test1",
      "icon": {
        "stack": "{id:\"minecraft:chest\",Count:1b}"
      },
      "action": {
        "key": {
          "key": "quark.keybind.change_hotbar",
          "toggle": true
        }
      }
    },
    "3": {
      "title": "test2",
      "icon": {
        "stack": "{id:\"minecraft:chain\",Count:1b}"
      },
      "action": {
        "key": {
          "key": "quark.keybind.lock_rotation",
          "toggle": true
        }
      }
    },
    "4": {
      "title": "test3",
      "icon": {
        "stack": "{id:\"minecraft:armor_stand\",Count:1b}"
      },
      "action": {
        "key": {
          "key": "quark.keybind.camera_mode",
          "toggle": true
        }
      }
    },

Maybe it's because quarks have keys that are quark.keybind.change_hotbar not key.quark.change_hotbar causing compatibility issues?

**Comment by GirafiStudios** [comment]
Should be fixed in 1.19
