### ISSUE TITLE
[Suggestion] API for other mods

### ISSUE THREAD

**Issue by Lgmrszd** [GirafiStudios/MineMenu#127]
Hello. I want to suggest adding API to this mod so that external mods can add custom actions not covered by keybinds.
Use-cases for that are mods that have their own system instead of keybindings, like showing gui on a specific keybind where you can alter the settings. With API from this mod, they could add toggleable actions for said settings, or maybe provide their own radial menus.

**Comment by GirafiStudios** [comment]
Thanks for the suggestion!
I have however no interest in adding something like this.
