### ISSUE TITLE
Can't change text language

### ISSUE THREAD

**Issue by Lunar94** [GirafiStudios/MineMenu#128]
Hi,

I saw the en_us lang file in the assets folder, but there is still a lot of missing translated text, could you fix it please ?

Ex:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/105256980/169717400-7a2a3400-4ccb-4674-8d1f-9c5ce3765312.png">

<img width="336" alt="image" src="https://user-images.githubusercontent.com/105256980/169717406-18a47be6-a427-4313-9884-681362b118ca.png">

Thank you so much !

Lunar

**Comment by Lunar94** [comment]
up please ! :)

**Comment by GirafiStudios** [comment]
I´ve added most of the strings as translatable, in the Minecraft 1.19 update :)
https://github.com/GirafiStudios/MineMenu/commit/40475064900c25055c3a93f4e09706087f8e87db
