### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Mshangao** [GirafiStudios/MineMenu#130]
Hello. I have this mod on 1.19, but it's not working. I have Mod Menu and he does not even see this mod :(

Is this for Forge? (I'm using Fabric)

**Comment by GirafiStudios** [comment]
Yes, this is a Forge mod. Clearly specified on CurseForge.

**Comment by Mshangao** [comment]
Do you know any similar alternatives for 1.19? I would really appreciate info

**Comment by DarkblooM-SR** [comment]
> Clearly specified on CurseForge.

Where?
