### ISSUE TITLE
Game Crashes after clicking the preset command button

### ISSUE THREAD

**Issue by AddictedCoins** [GirafiStudios/MineMenu#137]
The game crashed after clicking the preset command button on changing game modes, (ex: /gamemode survival) and the original game mode and target game mode do not affect this problem, it all crashes.

MacBook Pro 14" M1 Pro 16GB
6GB Ram Allocated
Minecraft 1.19.2
Forge 1.19.2-43.1.1
ItemZoom 2.7.0
***MineMenu 1.19.1-1.11.1***
WorldEdit 7.2.12
Optifine 1.19.2
Just Enough Items 11.2.0.256

**Crash Report Attached**

[crash-2022-08-31_09.33.32-client.txt](https://github.com/GirafiStudios/MineMenu/files/9463357/crash-2022-08-31_09.33.32-client.txt)

**Comment by AddictedCoins** [comment]
Single Player Mode, Cheat Activated, Click Action-Command Send
Just tested, all commands crash under the same circumstance

**Comment by AndrewRevenge** [comment]
Same here. Tried all 1.19 versions - no difference

**Comment by GirafiStudios** [comment]
> Same here. Tried all 1.19 versions - no difference

Are you using a Macbook with a M1 CPU aswell?

**Comment by AndrewRevenge** [comment]
Oh, no sorry, I missed that part. I'm actually using a standard windows
machine.

нд, 22 січ. 2023 р. о 11:52 Girafi ***@***.***> пише:

**Comment by nekomaster** [comment]
Yeah I'm having this issue as well with MineMenu with 1.19.2 on windows 10 with a an i5-9600K and GTX 1660 Video card (so no I'm not on a M1 or M2 mac)
Kinda sucks because its handy to have around to change gamemodes and do some very common WorldEdit stuff on 1.19.2

**Comment by GirafiStudios** [comment]
Should be fixed in the Minecraft 1.19.4 release of MineMenu :)
