### ISSUE TITLE
Modded keybinds refuse to work

### ISSUE THREAD

**Issue by TheUltimateGod4** [GirafiStudios/MineMenu#138]
I seem to be unable to get keybinds from mods to work with MineMenu. I can set it up perfectly fine, but when I actually go to use the keybind from the menu, nothing happens. Using the actual keys still works, and vanilla keybinds work perfectly fine.

Game Version: 1.16.5
Forge Version: 36.2.34
MineMenu Version: 1.8.7

I also use Curseforge if that is any help.

**Comment by TheUltimateGod4** [comment]
Okay so I was kind of wrong. The issue only seems to happen with certain mods' keybinds The mods that I know of that have this issue are listed below, along with their Curseforge links.

Kimetsu no Yaiba: https://www.curseforge.com/minecraft/mc-mods/demonslayer
Jujutsu Craft: https://www.curseforge.com/minecraft/mc-mods/sorceryfight
My Hero Academia: https://www.curseforge.com/minecraft/mc-mods/my-hero-academia
Devil Fruits: https://www.curseforge.com/minecraft/mc-mods/devil-fruits

**Comment by GirafiStudios** [comment]
Unfortunately I can´t add support for specific mods.
