### ISSUE TITLE
[1.18.2] [Bug] Using the radial menu to activate a key that is unbound in options.txt triggers all unbound keys simultaneously

### ISSUE THREAD

**Issue by KazuMurako** [GirafiStudios/MineMenu#142]
Minecraft 1.18.2
Forge 40.1.68
MineMenu 1.10.0

Using the radial menu to activate a key that is unbound in options.txt triggers all unbound keys simultaneously. This ruins most use cases for this mod as each key still needs a unique button assigned to it.

A possible solution could be assigning a dummy key to the keybind in options.txt, one that can only be activated by the radial menu, to prevent conflicts.
This issue exists in multiple versions as seen in issue https://github.com/GirafiStudios/MineMenu/issues/113

**Comment by GirafiStudios** [comment]
Closing as it´s the same as #113 as you mentioned.
