### ISSUE TITLE
Crash with some new mods

### ISSUE THREAD

**Issue by leofilhot** [GirafiStudios/MineMenu#143]
Hi. 
I was playing with some new mods to add in my server, then i added some new mods, that was:
Artifacts
Boatloads
Comforts
GrappleHooks
InvMove
ToolBelt
Abnormals delight

and the libraries 
expandability
kotlin for forge
abnormal's core/blueprint

and when i tested with this new mods in my modpack, it crashed. I actually use a lot of mods and never had that issue, 
in fact I've gotten very used to using the menu, but when i bind to open the menu, it crashes. Tomorrow maybe i'll try if i can see which of this mods its causing the crash, but do you know if there's some incompatiblity between one of those mods? 

I'm in 1.16.5 version.

**Comment by GirafiStudios** [comment]
As no crash logs is provided, I can´t really look into this.
