### ISSUE TITLE
Menu Not Selecting

### ISSUE THREAD

**Issue by TheTriwolf** [GirafiStudios/MineMenu#148]
(Disclaimer: This issue is with MineMenu being used in the modpack Medieval MC [FORGE] - MMC3 (Curse v16))

It lets me add items/commands/keybinds to the radial menu, but they don't work when I try to use them. When I try to attach a keybind or tool slot, it simply just closes the menu and doesn't use the tool or open the desired menu. When I try using a command in the menu, it crashes the game. It lets me created submenus and access them, but they also run into the same problems.

I'm guessing a mod inside the Medieval MC [FORGE] MMC3 modpack may be conflicting or something. Would there be any simple way to figure out how to fix this?

**Comment by GirafiStudios** [comment]
They´re still on 1.19.2 for whatever reason. All the issues have been fixed in later version for 1.19.4
1.19.2 is unsuported at this point.
