### ISSUE TITLE
Crash with using command

### ISSUE THREAD

**Issue by DragonMaster14545** [GirafiStudios/MineMenu#149]
I set up just a /say hi command in my pretty big modpack, but it crashes when using it. Everything else works fine. If this is not a problem with your mod, Im sorry I asked.
[crash-2023-07-03_18.41.34-client.txt](https://github.com/GirafiStudios/MineMenu/files/11938934/crash-2023-07-03_18.41.34-client.txt)

**Comment by GirafiStudios** [comment]
It is a problem with Mine Menu. But you´re using an old 1.19 version. Please update to the 1.19.4 version, as the problem is not present there.
