### ISSUE TITLE
Reason of 1.19.2 not working

### ISSUE THREAD

**Issue by Necxels** [GirafiStudios/MineMenu#155]
Hello, I've been reading multiple issues asking about the key binding error happening in the 1.19.2 version and I know you've stopped making updates for it but I've spend hours searching for the best version for a big modpack and 1.19.2 is still the best as of right now because a lot of mods or addons haven't been updated to latest versions of the game (and I mean a lot, arround 1/3 of the mods in my modpack ~ 150 mods)

I'm really sorry if you're tired of people asking for you to correct this bug so I'm going to ask for something a bit different :
- Could you please explain to us why it's not working in 1.19.2 (because you probably know why, you've corrected it in 1.19.4 ?) so that I can, at least, try to correct it myself ?

I need a mod like yours in 1.19.2 and you're litterally the only one doing this.

These are some of the mods I would have to drop if I changed my version of minecraft to 1.20.1 (because most mods skipped from 1.19.2 to 1.20.1) :
- **[Let's Do] Meadow** _by satisfy_
- **Another Furniture** _by Starfish_Studios_
- **Architect's Palette** _by Jsburg_
- **Blue Skies** _by ModdingLegacy_
- **Botania** _by Vazkii_
- **Every TeamAbnormals Mods**
- **Deeper and Darker** _by KyaniteMods_
- **Every Farmer's Delight Add-ons**
- **Doggy Talents** _by percivalalb_
- **Domestication Innovation** _by sbom xela_
- **Dynamic Trees** _by MaxHyper_
- **Enlightend** _by MuffinsQw_
- **Hexerei** _by JoeFoxe_
- **Immersive Engineering** _by BlueSunrize
- **Immersive Weathering** _by OrdanaryMods_
- **Immersive Portals** _by qouteall_
- **Infernal Expansion** _by InfernalStudios_
- **Integrated Dungeons and Structures** _by CraisinLord_
- **Integrated Stronghold** _by CraisinLord_
- **Mekanism** _by bradyaidanc_
- **More Villagers** _by SameDifferent_
- **Naturalist** _by Starfish_Studios_
- **Oh The Biomes You'll Go** _by AOCAWOL_
- **Quark** _by Vazkii_
- **Spirit** _by terrariumearth_
- **Tetra** _by mickelus_
- **The Bumblezone** _by telepathicgrunt_
- **Useless Sword** _by Furti_Two_
- **VillagersPlus** _by finallion_13_
- **Every YUNG's Mods**

Sorry if I disturbed you,
Hoping that I'll be able to add your mod to my modpack,
Have a good day.

**Comment by GirafiStudios** [comment]
I don´t have a branch for 1.19.2. Usually minor versions doesn´t have as many breaking changes, as 1.19.4
Mine Menu was not affected by those changes at all though.

I would have to recover the 1.19.2 source code, in order to fix it.

The mod is MIT, meaning the mod is public domain. Other people are very welcome to make their own 1.19.2 version with the fix, if they wish to do so.

**Comment by Necxels** [comment]
Ok, I understand.
Thank you
