### ISSUE TITLE
[1.20.1] Issue with menu selection

### ISSUE THREAD

**Issue by mahjerion** [GirafiStudios/MineMenu#156]
version: MineMenu-1.20.1-1.12.1

Seems to be an issue where when using the radial menu, after selecting the option you have to press the radial menu keybind to trigger it again > happens on release or click modes.

Similarly, selecting an option sometimes will trigger the selection in rapid succession.. The best example I can provide is using pMMO's show gui key in the radial menu, you will see pMMO's UI overlay flicker in and out rapidly.

If you need more information, I can provide. Would like to include this mod in my upcoming Craft to Exile modpack as I think it provides a very clean solution to keybinds.

**Comment by GirafiStudios** [comment]
Please try version 1.12.2 just uploaded on CurseForge, should hopefully fix the issue.

**Comment by GirafiStudios** [comment]
If this is still an issue in MineMenu version 1.20.1-1.12.2, please open a new issue :)
