### ISSUE TITLE
[1.20.1] Issue with menu selection (still)

### ISSUE THREAD

**Issue by mahjerion** [GirafiStudios/MineMenu#161]
Hi, just following up. There seems to still be issues with selection. I think the issue is slightly different now, as it's not working for some keybinds that open GUI.

Version 1.12.2
MC Version 1.20.1

For instance, I have bound FTB Quests GUI to U, and have it on my radial menu as a press. When I select it, nothing happens. However, I have Mine and Slash's GUI bound to H, and that seems to work.

**Comment by mahjerion** [comment]
It seemed to help.. some are working. But some work when I let go of the MineMenu key, some require me to click.

Selecting with toggle seems to help but sometimes nothing will happen when I let go, and then when I press the MineMenu key again it opens up. Eg. select FTB Teams GUI with toggle, let go --> nothing happens --> press MineMenu key --> FTB Teams GUI opens.

**Comment by GirafiStudios** [comment]
I´m afraid that´s about as good as I can get it.
Wonky is still better than not working at all!
