### ISSUE TITLE
[1.18.2] Selecting any keybind will activate all unbound keybinds

### ISSUE THREAD

**Issue by Catomax262** [GirafiStudios/MineMenu#163]
This is not a duplicate of the 1.20 one.

**Comment by GirafiStudios** [comment]
Minecraft 1.18.2 is unfortunately no longer supported.

**Comment by Catomax262** [comment]
That just sucks. There's tons of people who still prefer 1.18 over 1.20.

I'm playing in a modpack that only has 1.18 mods, and i need this because of troubleshooting.

**Comment by Catomax262** [comment]
If so, what can i do?
