### ISSUE TITLE
Crash before loading the game (fabric 1.20.4)

### ISSUE THREAD

**Issue by CallmeDome** [GirafiStudios/MineMenu#165]
Hello,

sadly I got issues with your mod. Installing and running the mod for the first, starts and working correctly. After closing the game and trying to restart, it crashes the game, before it even starts it. 

I'm pasting the crashlog below.
[crash-2024-02-09_18.26.42-client.txt](https://github.com/GirafiStudios/MineMenu/files/14224600/crash-2024-02-09_18.26.42-client.txt)

**Comment by GirafiStudios** [comment]
Unable to reproduce, with the steps mentioned.

Could  you provide your menu.json, found in the minemenu folder?

**Comment by CallmeDome** [comment]
Sure
[menu.json](https://github.com/GirafiStudios/MineMenu/files/14226180/menu.json)

**Comment by GirafiStudios** [comment]
Your menu.json is for sure broken. What exactly is causing it, I´m not quite sure.
