### ISSUE TITLE
[Bug|Incompatibility] Passive Skill Tree x MineMenu - can't assign skill tree shortcut on minemenu's radial menu

### ISSUE THREAD

**Issue by MetalKnight56** [GirafiStudios/MineMenu#166]
Minecraft Version: **1.20.1**
Forge Version: **47.2.20**
MineMenu Version: **1.12.3**
Passive Skill Tree Version: **BETA-0.6.9a-all**

Bug: When trying to assign the SkillTree open window keybind inside of MineMenu, it just won't let me actually use that keybind... Everything works, no crashes and the keybind is correctly assigned to the correct slot, the thing is, when it comes to actually using it, i'm unable to get it working, i press and nothing comes up...

Video showing the issue itself:
https://github.com/GirafiStudios/MineMenu/assets/77132244/ae44f59f-f9a7-4a05-975e-f2e5201e0400

**Comment by GirafiStudios** [comment]
Try changing it to Toggle (I assume it´s on Press). If t hat doesn´t work, I´m afraid you´re out of luck.
I unfortunately can´t really do anything to fix it.

**Comment by MetalKnight56** [comment]
> Try changing it to Press. If t hat doesn´t work, I´m afraid you´re out of luck. I unfortunately can´t really do anything to fix it.

Tried both xD

**Comment by GirafiStudios** [comment]
It´s not a problem on Passive Skill's end either (Most likely). It´s just very wonky to emulate keybind clicks.

**Comment by MetalKnight56** [comment]
> It´s not a problem on Passive Skill's end either (Most likely). It´s just very wonky to emulate keybind clicks.

Weird, i assumed they keybind control handler was kinda wonky, but seeing it now i'm intrigued as to why only this specific keybind has issues with MineMenu
