### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by kittenvr** [GirafiStudios/MineMenu#168]
is there a way to add all these keybindings to the menu instead of 1 by 1
![image](https://github.com/GirafiStudios/MineMenu/assets/103120356/48da0663-d785-4188-8f0c-e619e14e46b5)
![image](https://github.com/GirafiStudios/MineMenu/assets/103120356/6d1c3ed8-25a8-41d2-afc7-7af115644fe1)

**Comment by GirafiStudios** [comment]
There is not, unfortunately.

**Comment by kittenvr** [comment]
> There is not, unfortunately.

can you add it?
