### ISSUE TITLE
Fabric, 1.20.1. Big issue. Fix needed

### ISSUE THREAD

**Issue by Miamlya** [GirafiStudios/MineMenu#170]
My dear friend,

I hope this message finds you well. I'm reaching out regarding the release strategy for the MineMenu mod, specifically the absence of a Fabric 1.20.1 version. As an enthusiast of your mod and an active member of the Minecraft community, I'd like to express my concern about the decision to skip the 1.20.1 release.

**Request:**

I kindly request the release of the MineMenu mod for Fabric 1.20.1. This version appears to be favored by a significant portion of the player base, and its absence limits accessibility and enjoyment for many users, including myself.

**Reasoning:**

Player Preference: Fabric 1.20.1 remains a popular choice among players due to various factors, including mod compatibility and stability.
Community Feedback: Numerous discussions across community forums and social media platforms highlight the desire for MineMenu compatibility with Fabric 1.20.1.
Usage Patterns: Despite the availability of subsequent versions, many players continue to utilize Fabric 1.20.1, underscoring its importance within the Minecraft modding community.
Impact:

Enhanced Player Experience: Releasing MineMenu for Fabric 1.20.1 will ensure that a broader audience can enjoy the mod without the need to update to a different Minecraft version.
Community Satisfaction: Addressing this request demonstrates responsiveness to the community's needs and preferences, fostering a positive relationship between developers and users.
Mod Visibility: Compatibility with Fabric 1.20.1 will maintain the visibility and relevance of MineMenu within the modding ecosystem, potentially attracting new users who prefer this version.
Conclusion:
Considering the evident demand and the substantial usage of Fabric 1.20.1, I strongly believe that releasing the MineMenu mod for this version would greatly benefit the community. I appreciate your attention to this matter and eagerly anticipate a favorable response.

Thank you for your time and consideration.

**Comment by GirafiStudios** [comment]
There won't be any backports to 1.20.1 for Fabric or any version before.
The only reason I made a Fabric version, is because I started using MultiLoader to have both NeoForge and Forge versions, figured I might as well do Fabric going forward, while I was at it.
