### ISSUE TITLE
Selecting an item in the circular wheel will not lead to an action if the action is assigned with modifier key (ctrl, alt, shift)

### ISSUE THREAD

**Issue by somebush** [GirafiStudios/MineMenu#171]
I want to use MineMenu as a convenient access to rarely used but necessary actions. In large modpacks there are many more actions than can physically fit on the keyboard, so the rarest of them (which do not need to be pressed during combat or walking) would be good to assign in combination with Ctrl. For example, instead of pressing `u`, press `ctrl+u`.
But it doesn't work. I have Whyla - a fork of Waila, this mod adds hotkeys that change the information displayed on the screen. I assigned one of them to `Ctrl+F8`. MineMenu does not perform this action. I reassigned to `F8` - MineMenu performs this action.

version: MineMenu-1.12.2-1.6.11-universal.jar

**Comment by GirafiStudios** [comment]
Known issue, can't be fixed unfortunately.

1.12.2 have also not been supported for years

**Comment by somebush** [comment]
Anyway 1.12.2 is best version at march 2024. You're going the wrong way.

**Comment by GirafiStudios** [comment]
No, no it's not. 1.12.2 was released in 2017

**Comment by somebush** [comment]
1.12.2 has many more available mods than any other version.
