### ISSUE TITLE
Questions about translation...

### ISSUE THREAD

**Issue by Sunday40847** [GirafiStudios/MineMenu#172]
I'm trying to add a Chinese translation to this mod, and I'm curious about: (1.20.1 Forge)
1.Where can I find these words ↓ in game? I can't find a screen that contains them, thus unable to check my work.
<img width="405" alt="image" src="https://github.com/GirafiStudios/MineMenu/assets/86839110/bc562f12-a4e1-4785-bd2d-39b16503c587">
2.I can't find these words ↓ in the lang json. Are they editable?
<img width="515" alt="image" src="https://github.com/GirafiStudios/MineMenu/assets/86839110/d7c361de-a90c-4e4e-9aed-d8175cc8988e">
<img width="237" alt="image" src="https://github.com/GirafiStudios/MineMenu/assets/86839110/680cc2fe-04ae-4447-8f52-5e1ed3e6c7c4">
<img width="249" alt="image" src="https://github.com/GirafiStudios/MineMenu/assets/86839110/3f2b4b99-d79e-452e-8028-60cb6e7a45e2">

**Comment by GirafiStudios** [comment]
All the translation strings starting with "MineMenu" is never shown in-game. They're all used for the Minecraft text-to-speech functionality.

The gui.delete translation string, is for the "Delete" button when deleting something from the Radial Menu.

Hope that answers your question! :)

**Comment by Sunday40847** [comment]
thx for that. So I can't translate lines in Q2 right?

**Comment by GirafiStudios** [comment]
Unfortunately not atm. no.
