### ISSUE TITLE
My menu shortcuts aren't appearing

### ISSUE THREAD

**Issue by Cheet0Puff** [GirafiStudios/MineMenu#180]
I made some shortcuts in the menu but when I loaded up my game again they aren't there. I'm also confused because when I check the menu.json in the minemenu folder it still shows all of the shortcuts I made. It would be great if someone could tell me how to fix this :)

**Comment by Cheet0Puff** [comment]
There is also something rather strange. Whenever I load into my server I cant see any of the shortcuts but, when I load into a single player world I can only see half of them and the other half aren't even visible.

**Comment by Cheet0Puff** [comment]
I figured it out

**Comment by DeChillinGames** [comment]
> I figured it out

How did you fixed it? I'm having the same issue

**Comment by Cheet0Puff** [comment]
> > I figured it out
> 
> How did you fixed it? I'm having the same issue

Just go into a world before you join a server or just leave and rejoin or give it a while because it might just need time too load.
