### ISSUE TITLE
Keybinds not working on 1.20.1 Forge

### ISSUE THREAD

**Issue by RPink47** [GirafiStudios/MineMenu#181]
I have a 1.20.1 Forge modpack, and this mod doesn't seem to work with some keybinds. The mods I found it doesn't work with are: Ars Nouveau, Spartan Weaponry and Journey Map. I will elaborate more as I find stuff, thank you for your time.

**Comment by GirafiStudios** [comment]
That´s a common problem, due to difference in how mods utilize keybinds. Not much I can do on my end, that haven't already been done.

I would be willing to look into it, if it was for 1.21. All previous versions are now completely unsupported.
