### ISSUE TITLE
MineMenu not working on multiplayer servers

### ISSUE THREAD

**Issue by Gonaah** [GirafiStudios/MineMenu#182]
When opening Minecraft (1.21 Fabric), everything in the radial menu disappears on servers until I enter a singleplayer world. Any fixes?

**Comment by GirafiStudios** [comment]
Is MineMenu installed on the server as well?

**Comment by Gonaah** [comment]
No, its a public server. How does it work? Do you believe it is possible to prevent this from happening?

**Comment by Gonaah** [comment]
I already tried only with MineMenu & dependencies
https://github.com/user-attachments/assets/5270b647-986d-4b56-87e5-3d5c24ea11b6

**Comment by Gonaah** [comment]
Sorry I don't know how to use Github lmao

**Comment by 777hi** [comment]
I figured it out

**Comment by Gonaah** [comment]
> I figured it out

How?

**Comment by 777hi** [comment]
I made some modifications to the code so that the mod can also read the configuration file when entering the server

**Comment by Gonaah** [comment]
> I made some modifications to the code so that the mod can also read the configuration file when entering the server

Can you send it to me? I don't know how to code

**Comment by 777hi** [comment]
[minemenu.zip](https://github.com/user-attachments/files/17388188/minemenu.zip)

**Comment by berwulf** [comment]
W 

> [minemenu.zip](https://github.com/user-attachments/files/17388188/minemenu.zip)

**Comment by remidu64** [comment]
> [minemenu.zip](https://github.com/user-attachments/files/17388188/minemenu.zip)

what did you do exactly to get it to work ?
