### ISSUE TITLE
Unable to open some mod interfaces

### ISSUE THREAD

**Issue by wsxiya** [GirafiStudios/MineMenu#183]
I found that I can't open the Arrow Quiver interface of "Spartan Weaponry" and the backpack interface of "L2 Backpack". My game version is forge1.20.1-47.3.7, and all mods are the latest versions. I don't know if it's their reason. If so, please tell me.

**Comment by GirafiStudios** [comment]
Duplicate of https://github.com/GirafiStudios/MineMenu/issues/175
