### ISSUE TITLE
Upload to Modrinth

### ISSUE THREAD

**Issue by Bruhnanza** [GirafiStudios/MineMenu#185]
Hello,

MineMenu is an amazing mod that I use in my own modpack, but due to it solely being uploaded to Curseforge I must add it in separately. Having the project on Modrinth as well instead of just Curseforge would be beneficial for those who primarily use that platform and for modpacks hosted there, and expand the mod's reach for those who have left Curse. Would this be something you are open to?

**Comment by GirafiStudios** [comment]
I don´t really have any interest in uploading to Modrinth. I did attempt it with one of my other mods, but it took 2 months for it to get approved. I simply don´t have an interest to deal with that again

**Comment by Bruhnanza** [comment]
I understand, I would only add that I believe it has matured greatly and approval, moderation, and the site overall has seen a great amount of improvements. Just wanted it to be something you considered, but thank you for your continued work.

**Comment by GirafiStudios** [comment]
It was earlier this year, so I would like to see that being the case for a longer period of time :)
