### ISSUE TITLE
How do I set a keybind with   shift + [key]?

### ISSUE THREAD

**Issue by Ezzocorbi** [GirafiStudios/MineMenu#34]
I need to add a keybind that consists in pressing SHIFT + V, is it possibile to do so?

Also there's a mod called Ender Utilities which uses a lot of different keybinds that apparently are impossible to replicate with this mod because these keybinds aren't present in the "Controls" menu in Minecraft.
The mod by default just has a "toggle" key which is used with others keys. For example Ender Utilities adds a ruler to calculate distances and I can toggle an option for this item by pressing ALT + the toggle key (G by default). Apparently I can't add a keybind to the radial menu that lets me emulate ALT + G because the only keybind added by Ender Utilities in the Controls menu is G. Is there a way to add keybinds in the radial menu by manually pressing the buttons on the keyboard instead of selectig them in the Controls menu?
Thanks in advance.

![2018-07-03_10 36 34](https://user-images.githubusercontent.com/36800339/42208666-075367f0-7ead-11e8-84b2-e548b83c3632.png)
This is how many keybinds just one item from this mod has got.

![2018-07-03_10 38 39](https://user-images.githubusercontent.com/36800339/42208779-4d4e47a2-7ead-11e8-9478-cf5cab6cec39.png)
And this is the Controls menu, as you can see there's only a toggle key added by Ender Utilities.

**Comment by VADemon** [comment]
Bump. Same issue with TapeMouse: https://github.com/dries007/TapeMouse/issues/4

**Comment by phrayz** [comment]
Just wondering if this has been sorted out...?

**Comment by GirafiStudios** [comment]
Impossible with how Forge handles things related to "Shift +" or "Ctrl +" keybinds, and they won't change it.
