### ISSUE TITLE
Cannot bind some keys in Minecraft 1.7.10

### ISSUE THREAD

**Issue by HRudy94** [GirafiStudios/MineMenu#54]
Hey, i know this was already reported but a lot of keys don't work when i try to bind them...

The keys I've tested are the Drop Key, the Battle Inventory key from Battlegear, the MoCreatures GUI... All of them don't work. I can however bind the Inventory key just fine...

Can you fix this? (I know this mod hasn't been updated for 1.7.10 for a long time but this is a required fix...)

**Comment by GirafiStudios** [comment]
1.7.10 have not been supported for years.
