### ISSUE TITLE
1.8.9 Menu Bug

### ISSUE THREAD

**Issue by Linksvix99** [GirafiStudios/MineMenu#58]
Hi, I'm using the 1.8.9 version of MineMenu. I use Battlegear and Advanced Inventory, but when I tried using the setting for the battle inventory from Battlegear, nothing happened. I tried it with the inventory for Advanced, and it seemed to work, but when I closed out of it it reopened half a second later. So I closed it again. So it opened again. I did this several times, and then eventually gave up. I spammed Esc and got the pause menu up, but the menu STILL came up. I actually had to close out of Minecraft directly to exit the game. I even restarted and removed the option to open that inventory, and it came up anyway and I had to start again. Fortunately I found that clicking the LAN button prevents it from popping up on the pause screen so I didn't have to totally shut my game down. But is there any way you can fix this? Unfortunately I NEED it on 1.8.9, so simply just going to a new version won't do any good for me.

**Comment by GirafiStudios** [comment]
Unfortunately Mine Menu for 1.8.9 have not been supported for a long time. You can make a PR yourself to fix the issue, otherwise you're out of luck.
