### ISSUE TITLE
Texture Malfunction (and JourneyMap)

### ISSUE THREAD

**Issue by Linksvix99** [GirafiStudios/MineMenu#59]
I'm using the Iron Backpack mod. I set a slot on the menu to make a keybind link for opening a backpack and I use one of the mod's backpacks for the icon. When I restarted the client, though, it showed the "texturemissing" icon in its place. It happened several times in a row. At first I thought it was because I kept adding new mods between each time I restarted the client, but I closed it out then launched it again immediately and had the same problem. I also did a few other tests, and came to the conclusion that it is, indeed, the Iron Backpack mod. Bear in mind I'm using the latest 1.12.2 version of each of these. ...And as a side bug, when I set JourneyMap to open fullscreen with the keybind in MineMenu, nothing happens. I have to set a separate key.

**Comment by GirafiStudios** [comment]
I can't really do anything about Iron Backpack that's on their end.
As for JourneyMap, it should work. What Mine Menu version are you using?

**Comment by Linksvix99** [comment]
I thought I was using the latest, but as it turns out I mistakenly downloaded 1.6.9 rather than 1.6.10. I'll download that and see if it gets fixed, then get back to you with the results.

**Comment by Linksvix99** [comment]
As a side note, I can place waypoints - at least on single player, since that's the only time I'm able to get waypoints working. I just can't open the fullscreen map. Again, I'll let you know if updating fixes things.

**Comment by Linksvix99** [comment]
I just downloaded the 1.6.10 and tried the JourneyMap fullscreen thing again, but still no luck. And the texture for the backpack still doesn't appear, but I'll take your advice and let Iron Backpacks know about it.
