### ISSUE TITLE
Updated Issue - Keybinds Not Responding with Radial Menu

### ISSUE THREAD

**Issue by Linksvix99** [GirafiStudios/MineMenu#61]
I posted a bug report here a few weeks ago, and I have a major update. I've actually downloaded several mods with keybinds, and only a select few seem to work. Specifically, anything that has to do with item inventories. Apart from that, I only get vanilla keybinds working. I set it to JourneyMap's fullscreen or waypoint keybinds, nothing. I set it to the Overpowered Inventory GUI, no problems. Night Vision with Ender IO, no go. Baubles is just fine. Dynamic Sword Skills skill book, no. You get the picture. A few DO work, though, it's just a bit buggy. The Enhanced Armaments equipment level GUI works fine, except when I open it moving the mouse moves the camera, and when I exit the mouse is still visible, and what's more, it gets stopped by the screen edges. Toolbelt works fine with the belt equipping inventory, but the tool belt radial menu just appears and vanishes instantly even if I have it on toggle. Then again, radial menus probably weren't considered when coding a standalone radial menu mod. Still thought I'd bring it up, but I'm currently on MineMenu version 1.6.11. Know it only occurs with keybinds as far as I'm aware, as commands function properly, I have little to no use for the "item use" action and the category action just confuses me as to what it is or why it exists. Now, I did just test it with only MineMenu and Callable Horses installed, and it turns out to be a sort of conflict with another mod, though I play with several of them so I'm not going to go through them all myselfStill, the biggest selling point of MineMenu is that you can apply any key to an item in the radial menu. It's kind of a let down if you can't even use 90% of them just because of one conflicting mod.

**Comment by GirafiStudios** [comment]
What mod are you saying is causing the conflict exactly?

**Comment by GirafiStudios** [comment]
Closing because of no response.
