### ISSUE TITLE
JourneyMap's "Create Waypoint" doesn't seem to work

### ISSUE THREAD

**Issue by katubug** [GirafiStudios/MineMenu#62]
Hello! Firstly, thank you for the excellent mod! I'm working on a custom radial menu for my modpack, but I have a question and a potential bug.

The question is: If my players customize their radial menus, will their settings be overwritten with modpack updates, assuming I don't include the "menu.json"?

And the bug is that I can't seem to get the Journeymap's "Create Waypoint" keybinding to work with MineMenu. I'm referring to the one activated in-world, not the fullscreen-map "Create Waypoint." I have tried both "press" and "toggle" but neither have worked. I've also tested it out in an environment with only Journeymap, MineMenu, JEI and The One Probe, and the same issue persists.

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2846-universal
* **Modpack version** (links to current modlist): [1.7.1](http://enthusiasticraft.cf/modpack-update-1-7-1/#modlist)
* **Mod versions:** MineMenu-1.12.2-1.6.11-universal, journeymap-1.12.2-5.5.5

Here's a link to the latest.log from my test world: https://pastebin.com/z08Dvv5L

Please let me know if there's any other information I can provide!

**Comment by GirafiStudios** [comment]
It would only get overridden if you provide a menu.json by default in your modpack.
Unfortunately there is nothing I can do about fixing the issues with JourneyMap. There is a chance that this can be fixed in 1.14 since Minecraft uses a new system for keybindings, but since JourneyMap is not updated yet I cannot look further into it.

**Comment by katubug** [comment]
Ah, my bad! I didn't check to see if you were still supporting 1.12.2, sorry about that. Thank you for the quick response! :)

**Comment by katubug** [comment]
I apologize as this is slightly off-topic, but I don't think it's worth making another issue simply to ask you a question. Are there any other known issues regarding things that can be bound? I ask because I have attempted to add the Nutrition menu hotkey to the radial menu, and it doesn't work either. I'm assuming it's to do with a similar thing as the JourneyMap ones not working? And if so, is there anything I could look out for, so I don't waste your time with bug reports? haha

Thanks again for your time, it's appreciated!
