### ISSUE TITLE
Question: Is this mod required on both client and server?

### ISSUE THREAD

**Issue by katubug** [GirafiStudios/MineMenu#64]
Hi, I'm sorry to make an issue for this, but comments were turned off on CurseForge and I wasn't sure where else to get a hold of you.

Is MineMenu required to be on both client and server in order for it to be used in a multiplayer environment? Or is it clientside only?

Thanks for your time! :)

**Comment by GirafiStudios** [comment]
It is indeed :)
Actually I think some of the functionality will work with only being on the client-side, but for everything to work it's required on both sides.

**Comment by katubug** [comment]
Thank you very much! I appreciate the quick response! :D
