### ISSUE TITLE
Once a slot is set, how do I change it?

### ISSUE THREAD

**Issue by fuzzyweapon** [GirafiStudios/MineMenu#67]
It's unclear to me how I can modify pieces of the wheel that have already been set.  D:

**Comment by AstragoYT** [comment]
Go to C:\Users\YOUR USERNAME\AppData\Roaming\.minecraft\config
in the minemenu-common.toml (open with a text editor) you can change the option "rightClickToEdit" to true. 
or just change the whole file to this:


[general]
	toggle = false
	rightClickToEdit = true
	releaseToSelect = false
	menuAnimation = true
	menuButtonIcon = "minecraft:stone"

[visual]

	[visual.menu]
		#Range: 0 ~ 255
		alpha = 153
		#Range: 0 ~ 255
		red = 0
		#Range: 0 ~ 255
		green = 0
		#Range: 0 ~ 255
		blue = 0

	[visual.select]
		#Range: 0 ~ 255
		alpha = 153
		#Range: 0 ~ 255
		red = 255
		#Range: 0 ~ 255
		green = 0
		#Range: 0 ~ 255
		blue = 0

**Comment by AstragoYT** [comment]
Or just press shift

**Comment by GirafiStudios** [comment]
Thanks for explaining it @AstragoYT 
The path mentioned above is only correct if you have Forge installed in your vanilla launcher. "minemenu-common.toml" will be located in the config folder for whatever installation you have - depends on the launcher.
