### ISSUE TITLE
Unable to re-write slots?

### ISSUE THREAD

**Issue by brownie310500** [GirafiStudios/MineMenu#68]
is it possible to delete a bind you've already made. its quite easy to mess up a spelling or set to copy instead of send so would be cool to have a wipe selection or something. unless there is one and im just missing it but im struggling i guess.
thanks!

**Comment by GirafiStudios** [comment]
Shift-click the button

**Comment by brownie310500** [comment]
well that was alot easier than first thought, maybe could label this somewhere as spoons like me might not have the brain capacity to work it out ahaha, thanks anyway!

**Comment by GirafiStudios** [comment]
Information added to CurseForge.
