### ISSUE TITLE
1.15.2 Crash

### ISSUE THREAD

**Issue by MoistShy** [GirafiStudios/MineMenu#69]
Running Forge 31.1.0 with these mods
jei-1.15.2-6.0.0.2 (Just enough items)
Hwyla-forge-1.10.7-B71_1.15.1 (Heres what you're looking at)
MineMenu-1.15.1-1.8.3 (Self explanatory)
Opening Minemenu is fine until i try and click a submenu
only then does my game force me to the main menu and proceed to crash

**Comment by GirafiStudios** [comment]
Fixed in https://github.com/GirafiStudios/MineMenu/commit/2cbff182302fb898ef33ed9e8263b84b1e8552c2
