### ISSUE TITLE
Game crash while exploring menu

### ISSUE THREAD

**Issue by Piston35** [GirafiStudios/MineMenu#71]
I was just trying this mod out for the first time and looking around the features in the menu when the game crashed with:
"Error: java.lang.IllegalArgumentException: The value 32996 is not in the specified inclusive range of 0 to 32767"

This is on Minecraft 1.15.2, forge version 31.1.39, MineMenu version 1.8.4.

Here is the crash report: [crash-2020-04-09_15.17.34-server.txt](https://github.com/GirafiStudios/MineMenu/files/4458493/crash-2020-04-09_15.17.34-server.txt)

I haven't been able to get it to happen again. I was on the Click Action: Category menu and it crashed when I clicked cancel (or very nearly before or after I clicked).

**Comment by GirafiStudios** [comment]
Thanks for the report!
I'll take a look at it sometime next week.

**Comment by GirafiStudios** [comment]
Got a chance to take a proper look at it.
The crash is related to code that determines the color variation of grass block, leaves etc. in each biome.
There is a few mods that've made mixin changes that's related to the code, which is mostly Immersive Portals - Quark & Phospor a little bit.
I can for sure say that this has nothing to do at all with Mine Menu, just a coincidence that the crash occurred while using Mine Menu.
