### ISSUE TITLE
How can i disable movement after entering a menu from minemenu

### ISSUE THREAD

**Issue by zombiko** [GirafiStudios/MineMenu#76]
Keybinding a menu to radial such as a guidebook mod or any mod with a menu a problem appears. When u enter the menu  from the radial the players camera can still move around in background and their original mouse cursor is stuck on screen until radial is reopen. Was wondering if theres a way to disable camera during this command and also prevent mouse cursor to remain after radial is close.

**Comment by GirafiStudios** [comment]
What version of Mine Menu are you using?

**Comment by zombiko** [comment]
> What version of Mine Menu are you using?

1.6.11 for minecraft version 1.12.2

**Comment by GirafiStudios** [comment]
Unable to reproduce for Minecraft 1.16.4. Minecraft 1.12.2 is unsupported now.
Please let me know if you're able to reproduce it on Minecraft 1.16.4
