### ISSUE TITLE
it says unknown command

### ISSUE THREAD

**Issue by imprx** [GirafiStudios/MineMenu#77]
i have a keystrokes mod that gets activated when you do a command. /keystrokesmod and it doesnt come up. it just gives me an error saying unknown command do /help. if you could fix this im using 1.8.9 cause pvp sucks anything after that

**Comment by GirafiStudios** [comment]
That have nothing to do with Mine Menu at all.
Using HelpFixer should fix your issue: https://www.curseforge.com/minecraft/mc-mods/helpfixer/files

**Comment by imprx** [comment]
error still persists
