### ISSUE TITLE
A new MineMenu Bug

### ISSUE THREAD

**Issue by CR2814740** [GirafiStudios/MineMenu#80]
Every Icon for MineMenu to differentiate every different command is all empty and the textures are gone besides the container items like chests and shulker boxes.
![2020-07-04_00 06 49](https://user-images.githubusercontent.com/67296715/86507121-68d2bf80-bd8a-11ea-9136-8f5a0a2a8628.png)

**Comment by GirafiStudios** [comment]
What version are you on?

**Comment by CR2814740** [comment]
The newest one, Forge 1.16.1.

**Comment by GirafiStudios** [comment]
How exactly did you replicate the issue?
Also what version of Forge are you using?

**Comment by GirafiStudios** [comment]
Unable to reproduce
![KnGQSQO](https://user-images.githubusercontent.com/6305377/86635332-3d8ee100-bfd3-11ea-984e-23b5d897b121.png)
Commands are working fine as well.
