### ISSUE TITLE
Incompatible with GUI Scale Hack

### ISSUE THREAD

**Issue by ChromaPIE** [GirafiStudios/MineMenu#81]
About GUI Scale Hack: https://www.curseforge.com/minecraft/mc-mods/gui-scale-hack

Screenshot: https://imgur.com/a/c3aYemr

Screenshot showing another scale-tweaked GUI (for comparing): https://imgur.com/a/OlD3zPS

**Comment by GirafiStudios** [comment]
Don't intend to add support.
