### ISSUE TITLE
[Suggestion] Fabric Support 1.16+

### ISSUE THREAD

**Issue by GenSecrets** [GirafiStudios/MineMenu#84]
Hello!

As a lot of my most commonly used mods are fading away from Forge and picking up Fabric, I was wondering if you'd ever consider a Fabric variant of MineMenu (since the entire purpose of Fabric is ease of updating in between MC versions). The bulk of my mods that have started the conversion didn't really pick up until about 4 or 5 months ago or more, I guess roughly around the time of 1.15 maybe?

I would also monetarily contribute to the quick development of a Fabric version if this is needed as I love this mod but can't use it since I now have a few other mods that are dropping Forge support in favor of Fabric. Would love the consideration, if not now then maybe soon in the near future. :)

**Comment by GirafiStudios** [comment]
Thank you for asing very nicely!
But no, I'm not gonna support Fabric for any of my mods ever. A lot of Fabric users have been extremely rude to me. They've been leaving rude comments on CurseForge about my mod(s) being Forge or the fact that I didn't have a Fabric version of the mod.
Also there were a case a couple of months ago, where someone were spamming the Forge Github repo with new issues just saying "Fabric master race", I don't want to support that kind of childish behavior.
I was originally planning to have Fabric support for some of my smaller mods, as I do know Modmuss semi well.

**Comment by GenSecrets** [comment]
I hate to hear that about your experiences with them, that really stinks. I've always been a fan of treating others with respect regardless of where or how you meet them. Nonetheless, thank you for the clarification! Should you ever be interested and decide to pick up the support for fabric, reopen this issue and I'll gladly support its development monetarily as im a big fan of your mods. Thank you still!

**Comment by UltraBlackLinux** [comment]
@GirafiStudios 
Hey, 
Firstly; yes, you already decided about this, but please rethink your decisions:
Every modding community has dicks, and I am pretty sure, also forge kiddies have done such scuffed stuff already, but the majority of both is nice and open-minded. 
The fabric modloader is - for now at least - the future. It's a very fast modloader with a way too tiny api (lol).
I don't think, that completely turning away from fabric is a solution.
This mod is such a wonder- and powerful tool, to manage commands and more. For long, I have used this mod on servers, but then I switched to 1.16 Fabric, for the amount of clientside mods, the loading speed and the ease of use.
I would really love to work together with you and assist you with porting this mod to Fabric (I have some experience with it).
Best regards,
UBL.

**Comment by GirafiStudios** [comment]
I appreciate the interest in this, but I will never allow any of my mods on Fabric anymore.
It's not a matter of it being difficult, it's actually quite easy - I simply not gonna allow any of my mods on Fabric ever.
