### ISSUE TITLE
[feature request] sub folders

### ISSUE THREAD

**Issue by iceyrazor** [GirafiStudios/MineMenu#86]
I think it would be even cooler if you could basically do folders inside the menu. adding even more. so the wheel could either be a key bind or a folder. and then in a folder can only be a key bind. so the first set of 10 can be a folder. but all folders can only have key binds from that point. (to save the amount of data being used.

**Comment by GirafiStudios** [comment]
You can already do that, it's called "Categories".

**Comment by iceyrazor** [comment]
OH xd sorry

**Comment by iceyrazor** [comment]
i didnt see anything related to that on the main page so i just assumed.

**Comment by iceyrazor** [comment]
and now i see it. i must be blind
