### ISSUE TITLE
1.15.2 Menu keeps resetting button

### ISSUE THREAD

**Issue by Hiranus** [GirafiStudios/MineMenu#87]
As said in the title, I tried setting it up for Traveller Backpack mod open backpack action, but after I close MC and open it up again my binding is gone. I tried setting it up for action from vanilla and it is not reset.

In log I found this: 
[m[33m[10:25:49] [modloading-worker-2/WARN] [MineMenu/]: Menu item in slot 0 is defined as a key action, but is missing a keybinding. It will be reset!

And here is content of menu.json
`{
  "Backpack": {},
  "main": {
    "0": {
      "title": "Backpack",
      "icon": {
        "stack": "{id:\"travelersbackpack:standard\",Count:1b,tag:{}}"
      },
      "action": {
        "key": {
          "key": "key.travelersbackpack.inventory",
          "toggle": false
        }
      }
    },
    "1": {
      "title": "123",
      "icon": {
        "stack": "{id:\"minecraft:stripped_spruce_wood\",Count:1b}"
      },
      "action": {
        "key": {
          "key": "key.left",
          "toggle": false
        }
      }
    }
  }
}`
Is it possible to fix it somehow? If not then I have 2 ideas that I hope can fix this:
1. Add option in config that will do force 'late load' of your keybindings, for example during world load.
2. Add command `/minemenu reload` that will tell your mod to reload minemenu because user requested it.

**Comment by Hiranus** [comment]
It looks like same issue as https://github.com/GirafiStudios/MineMenu/issues/75 .

**Comment by GirafiStudios** [comment]
Closing as it's the same as #75, as you mentioned yourself.

**Comment by Netizenswen** [comment]
The same problem occurred with 1.21.1, but my version is 1.21.4. After restarting the game, all menu configurations are gone. I am also a Chinese player, and my English may not be very good.
