### ISSUE TITLE
Remove macro or rename?

### ISSUE THREAD

**Issue by Physalia77** [GirafiStudios/MineMenu#89]
Hey, I made a macro in your MineMenu but wanted to rename it and delete a category but then I saw there is no way to do that. Or maybe I just missed it but I didn't find anything to delete category or rename a macro.
I would love to see those 2 things being added to your mod (if that doesn't exist already and I just missed it). Love your mod, thanks!

**Comment by GirafiStudios** [comment]
Hold Shift, when clicking the menu button in order to edit and/or delete it.
