### ISSUE TITLE
[feature request] 5 commands to one bind

### ISSUE THREAD

**Issue by iceyrazor** [GirafiStudios/MineMenu#90]
the ability to run up to five commands at once would be nice. and maybe also a adjustable timeout between each command. up to 5 seconds or something

**Comment by GirafiStudios** [comment]
Thank you for your suggestion!
That's without the scope of the mod, so won't get added.

**Comment by iceyrazor** [comment]
> Thank you for your suggestion!
> That's without the scope of the mod, so won't get added.

what do you mean "without the scope"? you can allready run commands such as chat or /say hello. how hard would it to be to add the ability for more commands? should be the same as commands but then just running another chat command? please explain.
