### ISSUE TITLE
Screen moving in GUis

### ISSUE THREAD

**Issue by Jerome226** [GirafiStudios/MineMenu#92]
I use the latest version of the mod for 1.12.2 : MineMenu-1.12.2-1.6.11-universal.jar

My head is moving when i'm moving my mouse in the GUIs.
![image](https://user-images.githubusercontent.com/55724525/104797285-e9876500-578a-11eb-85e3-18715803c072.png)

**Comment by GirafiStudios** [comment]
Duplicate of #76
