### ISSUE TITLE
Selecting Unbound Keybind Triggers All Unbound Keybinds

### ISSUE THREAD

**Issue by Brittank88** [GirafiStudios/MineMenu#94]
`Minecraft 1.16.4`
`Forge 35.1.37`
`MineMenu 1.8.7`

Selecting an unbound keybind currently means that every time that menu entry is selected, ALL unbound keybindings are activated at once.

There's nothing in the logs to show, and no crash occurs, however, if you still wish for me to post the logs let me know!

**Comment by Brittank88** [comment]
P.S. Unrelated but does MineMenu support some of the more 'out there' MC-supported keybindings such as F13-F25?

**Comment by GirafiStudios** [comment]
Nothing that can be done about that, that's just how vanilla treats it.

**Comment by Brittank88** [comment]
That's a shame, but I understand!

Just thinking outside the box real quick - is there no way to direct the keypress event to *only* the specific mod being targeted? I'm not a Java / FML expert, I'm not sure what the limitations are...
