### ISSUE TITLE
Keybind ( Attack/Destroy , Toggle) not working

### ISSUE THREAD

**Issue by noobimpostor** [GirafiStudios/MineMenu#97]
I made shortcut to AfK Mining. Set keybind Attack/Destroy with Toggle. It justs animates my pickaxe is attacking but not working.

MC Version : 1.16.5
Forge: 36.0.x

**Comment by noobimpostor** [comment]
Whilst the Use/Place works correctly

**Comment by GirafiStudios** [comment]
That is working as intended. You're not meant to be able to be able to use Mine Menu as a AFK mining tool.

**Comment by noobimpostor** [comment]
🥺😢
